# Generated by Django 4.0.2 on 2022-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=40)),
                ('role_name', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('remark', models.CharField(max_length=40)),
            ],
        ),
    ]
